
### CREATE MARKET DATA FUNCTIONS TO OBTAIN THE BELOW AUTOMATICALLY ###

# Spot symbol from Binance 
binance_symbol: XMRUSDT 
binance_tick_size: 0.0005
binance_lot_size: 0.01 

# Futures symbol from Bybit
bybit_symbol: XMRUSDT 
bybit_tick_size: 0.0005
bybit_lot_size: 0.01 

# Primary data feed (BYBIT or BINANCE) 
# Check README.md for more info regarding this 
primary_data_feed: BINANCE 

# A multiple of the tick size
# Prevents a 'ping-pong' effect
buffer_multiplier: 5 

# Account info ($)
account_size: 50  

# Settings for volatility indicator 
bollinger_band_length: 13
bollinger_band_std: 2

# Master offsets 
quote_offset: +0.0 # Increases quote price in base units
size_offset: +0.0  # Increases quote size in quote units
volatility_offset: +1.0 # Increases quote range in base units

# Settings for Market Maker function 
target_spread: 0.1 # In quote asset unit
number_of_orders: 10 # Total number of orders
minimum_order_size: 1.0  # In base asset unit
maximum_order_size: 7.5  # In base asset unit

# Extreme value for inventory
# Check README.md for more info regarding this 
inventory_extreme: 0.5  
